// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnmybKG-4Y0bOUuylssovqNG-PtzDxRbY',
    appId: '1:584737786238:web:52578fd574f42c4cfd0b2f',
    messagingSenderId: '584737786238',
    projectId: 'fir-b22de',
    authDomain: 'fir-b22de.firebaseapp.com',
    storageBucket: 'fir-b22de.appspot.com',
    measurementId: 'G-MEDCWLJ1VK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzOOGiGOpiczACNYNdP9vY9P7c7vjgv-A',
    appId: '1:584737786238:android:181b16c648999c39fd0b2f',
    messagingSenderId: '584737786238',
    projectId: 'fir-b22de',
    storageBucket: 'fir-b22de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASbUtZsmO3Kh2NQUSj3rjClNjaOJeUPh4',
    appId: '1:584737786238:ios:d42269387673c4ccfd0b2f',
    messagingSenderId: '584737786238',
    projectId: 'fir-b22de',
    storageBucket: 'fir-b22de.appspot.com',
    iosBundleId: 'com.example.fireBase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASbUtZsmO3Kh2NQUSj3rjClNjaOJeUPh4',
    appId: '1:584737786238:ios:d42269387673c4ccfd0b2f',
    messagingSenderId: '584737786238',
    projectId: 'fir-b22de',
    storageBucket: 'fir-b22de.appspot.com',
    iosBundleId: 'com.example.fireBase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnmybKG-4Y0bOUuylssovqNG-PtzDxRbY',
    appId: '1:584737786238:web:1c93092481ab558dfd0b2f',
    messagingSenderId: '584737786238',
    projectId: 'fir-b22de',
    authDomain: 'fir-b22de.firebaseapp.com',
    storageBucket: 'fir-b22de.appspot.com',
    measurementId: 'G-MY8ZW43M57',
  );
}
